openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: 'ワークフロー画面のバックエンドのAPI群。モックとしても使用する。'
servers:
  - url: 'http://localhost:8080'
    description: 'ローカル環境'
  - url: 'https://wf-rest.herokuapp.com'
    description: 'デモ環境'
paths:
  /users:
    $ref: './paths/users.yaml'
  /users/{userId}:
    $ref: './paths/usersId.yaml'
components: # 再利用部品。$refsで参照する
  parameters:
    $ref: './components/parameters/index.yaml'
  schemas:
    $ref: './components/schemas/index.yaml'
externalDocs:
  description: 'Find out more about Swagger'
  url: 'http://swagger.io'
